### ISSUE TITLE
[Feature request] pacman’s NoExtract

### ISSUE THREAD

**Issue by concatime** [void-linux/xbps#165]
Hi. It would be awesome if we could simply exclude files/directories from getting extracted. For example, I want to skip `/usr/lib/firefox/fonts` and `/usr/lib/firefox/browser/features`. I asked on `freenode#voidlinux`, but it seems there is no way for now.

**Comment by Vaelatern** [comment]
Why is this an important feature?

**Comment by Anachron** [comment]
Could we maybe add a more general way of triggers/hooks in xbps? Maybe some way to hook into `xbps` events like `/etc/xbps/triggers/{pre,post}-{install,extract,remove}` or alike.

**Comment by concatime** [comment]
@Vaelatern Well, you can skip parts of packages that you find redundant. Firefox ships its own emoji font (Twemoji Mozilla), but I already have one installed on my system (ttf-symbola).

**Comment by Johnnynator** [comment]
The other way around would be to just split packages more of we think some parts of it are unnecessary so they can be ignored with `ignorepkg`

**Comment by concatime** [comment]
Package splitting is not a viable solution: 1. More storage 2. Less flexibility
For example, I want want neither firefox’s fonts, nor default add-ons (`/usr/lib/firefox/browser/features/*.xpi`).
1. firefox
2. firefox-no-fonts
3. firefox-no-addons
4. firefox-no-fonts-no-addons

**Comment by Duncaen** [comment]
I think this would be good to add, we already have `preserve` which is similiar, but because of how it works is not usable in this case.
This would also be nice for containers, where you `skipextract=/usr/share/man` to cut down the size even more.

It is easy to implement and I already had it on my todo.

**Comment by concatime** [comment]
How about mimicking pacman? https://git.archlinux.org/pacman.git/tree/lib/libalpm/util.c#n1454

**Comment by Johnnynator** [comment]
Pacman is just using `fnmatch(3)` with the addition that also inverted patterns are allowed to guard files.

**Comment by Chocimier** [comment]
I would use that to remove all translations (0.5 GiB out of 10 GiB /usr) except pl_PL. Negative patterns would help for that.

> if `/usr/share/man` would be interpreted like `/usr/share/man/*`

Any way is good, but let it be consistent with preserve (globbing against package content?).

**Comment by Duncaen** [comment]
> Any way is good, but let it be consistent with preserve (globbing against package content?).

globbing works on real files, `/usr/share/man/*` would only preserve `man1`, `man2` etc, because it is once expanded when the configuration is read and it doesn't do like prefix matching, only checks if the complete path is in preserve.

So if we want to have it exactly like glob, we would need to write our own glob implementation that expands the paths using all the files and directories every package contains.

I think a simple `fnmatch` like in pacman would be simpler, easier to understand and write because you don't have the shell to test your patterns.
Even if it behave slightly different, the `preserve` behavior sucks and preserving deeply nested directories mixed with files would require weird patterns because we can't use any of the GNU glob extensions.

**Comment by Chocimier** [comment]
> /usr/share/man/* would only preserve man1, man2

Let's not do this then.

**Comment by concatime** [comment]
@Chocimier Where do you find translations?
```sh
find /usr -name pl_PL
# /usr/share/i18n/locales/pl_PL
du -hs /usr/share/i18n/
# 17M     /usr/share/i18n/
```

**Comment by Chocimier** [comment]
/usr/share/locale, just checked and there is more files in pl that pl_PL.

**Comment by xtraeme** [comment]
@Duncaen any update?

Note that pkg files metadata will need to be updated accordingly, otherwise xbps-pkgdb will find lots of unexistent files.

**Comment by xtraeme** [comment]
hmm or rather than modify the meta files, update xbps-pkgdb to take into account the `noextract` settings in xbps.d.

**Comment by Duncaen** [comment]
I did not work on this. I think `fnmatch` in `xbps-pkgdb` is fine, shouldn't be slow unless you have like thousands of patterns to check.
But maybe we could make it `noextract=[pkgname:]pattern` with optional pkgname so that you can make patterns match against specific packages instead of all.

**Comment by imrn** [comment]
Package request for localepurge may also be related with this:

https://github.com/void-linux/void-packages/issues/18125#issuecomment-572675667

**Comment by imrn** [comment]
I guess it is much better not to install unnecessary files during package extraction. Deleting them later by some tool like localepurge is only a workaround. If NoExtract or a similar functionality would be implemeted soon, then we can skip the request for localepurge.

Any rough ETA for NoExtract?

I bet, the very first use of this functionality will be to implement something like localepurge. Unused locale related files wastes a lot of precious disk space especially on a SSD. And they cause unnecessary wear with unnescessary erase-write cycles with considerable volume.

**Comment by imrn** [comment]
May be we can think something like /etc/xbps/noinstall.d/ in which we can
drop our "do not install" definitions.
