### ISSUE TITLE
xbps-install -Sy foo fails, performs unexpected action, exits zero

### ISSUE THREAD

**Issue by roman-neuhauser** [void-linux/xbps#166]
when i run `xbps-install -Sy foo`, i expect xbps to either install `foo` or fail.  instead, it does something else (updates libxbps/xbps) and claims success (exits zero) even though it clearly failed to do what was requested, not to mention it did something i didn't ask for *instead*.

the man page lacks any mention of this POLA violation, as well as recommendations regarding reliable unattended use.

**Comment by Duncaen** [comment]
The point of updating libxbps and xbps before doing any other updates is to allow to hotfix issues in case it is required.

This issue https://github.com/void-linux/xbps/issues/142 describes the same problem which we are facing in `xbps-src` after every xbps update.

The problem is that its hard to fix imo, people started to use `xbps-install -Su && xbps-install -Su` in scripts to work around it.

I think we shouldn't remove the mechanism, in case something goes very wrong we can fix issues before users will be affected by bugs and the last time we had to make use of this feature was less than a month ago.
https://voidlinux.org/news/2019/08/xbps-bug-results-in-missing-bin-sh.html

One of the last release tried to make the mechanism more bullet proof by also updating xbps itself alone when installing or updating another specific package.

One solution would be to reexecute xbps-install with the same arguments when it updated itself first, but there are some edge cases which are not easy to fix.

Another solution would be to just not allow any update and exit with `ENOTSUP` or any other error code until the user updates xbps, which would require unattended installations to check the exit code and then try to update xbps and then the original action.

In both solutions and the current implementation if `xbps-install` is used with a separate root directory the hotfix mechanism is useless because it never updates the actual xbps installation that does the installation.

I'm really not sure what the best way to go forward would be and how to tackle the different rootdir issues.

**Comment by Chocimier** [comment]
> I'm really not sure (…) how to tackle the different rootdir issues.

Do update-in-memory analogous to memory-sync?

More serious, I agree it would be better when `xbps-install bar` return error that update xbps and call it a day.

**Comment by xtraeme** [comment]
After reading this thread I came to the conclusion that it is better to return an appropiate error code and a message explaining that `xbps` needs to be updated, i.e:

``` # xbps-install foo
       The `xbps` package needs to be updated to `0.60`, please run `xbps-install -u xbps`.
      #
```

What do you think?

**Comment by roman-neuhauser** [comment]
> After reading this thread I came to the conclusion that it is better to return an appropiate error code and a message explaining that `xbps` needs to be updated

> What do you think?

i'm all for it!  please make sure to use a dedicated exit code to make this particular condition easily detectable in scripts.

the remaining question is, what should happen on `xbps-install -u`.  i haven't thought it through but it looks like the same reaction would work.
