### ISSUE TITLE
xbps-install a package with no dependency

### ISSUE THREAD

**Issue by bgkillas** [void-linux/xbps#203]
why cant there be a option to install a package and not its dependencys seems stupid how xbps-remove -F exist but no way to do that in installation

**Comment by flexibeast** [comment]
i'm intrigued as to the use-case for this. Could you please explain why you'd want to install a package that you can't actually *use* because its dependencies haven't been installed?

**Comment by bgkillas** [comment]
some things have dependencys that may not be requiered for your use case for example git you dont need perl really or any dependencys that it may or may not install for you but if you dont want them why should you have to go threw the trouble to uninstalling them manually like that 
prob some other things id use it for but dont remember rn

**Comment by flexibeast** [comment]
If something is not a hard dependency, then whether to include it as a dependency or not will depend on what the package maintainer thinks is most appropriate, e.g. in terms of the most common use-case: if it's not a hard dependency, but the majority of people install it anyway, it makes sense to have it as a dependency. Whatever the decision, *someone* is going to be inconvenienced.

i don't know whether XBPS distinguishes (or can distinguish) between soft and hard deps, which i would guess would be necessary to support the sort of option you describe. Otherwise the option could result in avoiding installing one or two soft deps, yet require the user to then manually install e.g. half a dozen hard deps.

**Comment by xtraeme** [comment]
even if `pacman -Sdd` exists, I don't really care. What is stupid is to install a package without its required runtime dependencies.

**Comment by Duncaen** [comment]
There is the `ignorepkg` configuration option, see https://man.voidlinux.org/xbps.d.
This allows you to ignore certain dependencies, but will not allow to ignore all of them, it won't allow to remove dependencies that are required because of shared libraries to be certain.
