### ISSUE TITLE
[Help wanted] Force reinstalling every package 

### ISSUE THREAD

**Issue by 0xatul** [void-linux/xbps#308]
How do I force reinstall every package I ever installed?
 I messed up some permissions on the root of the distro and that seems to be the fix apparently

**Comment by Duncaen** [comment]
There is currently no specialized option to do that, you would have to get a list of all packages with `xbps-query -l` and force reinstall those packages.
Something like `xbps-install -f $(xbps-query -m)` should work.
Otherwise you could use `xbps-pkgdb -a` and filter the output to get a list of actually broken packages to reinstall.

**Comment by 0xatul** [comment]
thanks for the help :)
