### ISSUE TITLE
xbps-remove -On listing differs between running as root vs non-root

### ISSUE THREAD

**Issue by z33ky** [void-linux/xbps#357]
I wanted to check out that `xbps-remove -O` will only delete obsolete packages as promised using `-n`, but was quite surprised at the listing I received, which contained lots of currently installed packages.
Eventually I figured out, that running it as root instead provides a correct listing.

So currently I get the following output (the `#`-prefixed parts are added by me):
```
$ sudo xbps-remove -On
# empty
$ xbps-remove -On
Removed soundtouch-2.1.2_1.x86_64-musl.xbps from cachedir (obsolete)
Removed libpng-devel-1.6.37_1.x86_64-musl.xbps from cachedir (obsolete)
Removed libedit-20191231.3.1_1.x86_64-musl.xbps from cachedir (obsolete)
# ... lots more
$ xbps-query soundtouch|grep '^pkgver'
pkgver: soundtouch-2.1.2_1
```

That behavior seems wrong to me. I would expect `xbps-remove -On` to return the same listing.
If this is due to some kind of permission problem it should print an error, though I doubt that is the case since `/var/cache/xbps` is world-readable and running `xbps-query` as non-root also returns correct information for currently installed packages.

**Comment by Duncaen** [comment]
This was most likely due permissions, some old packages in the cache prior to the umask changes might not be readable by "other".

 `xbps-remove -O` will not only delete obsolete packages but will also checksum current packages and delete them if the checksum doesn't match. Since reading the checksum didn't work it just "dry removes" the file from the cache.
The PR https://github.com/void-linux/xbps/pull/444 fixes that by not "dry removing" the file and printing an error instead.
