### ISSUE TITLE
INSTALL pre script could run with no libc

### ISSUE THREAD

**Issue by ArsenArsen** [void-linux/xbps#382]
due to `INSTALL` scripts being able to run, on update, after removing a packages files, and before reinstalling them, libc `INSTALL` scripts will be ran with no libc installed.

This is currently blocking https://github.com/void-linux/void-packages/pull/29103  
Related code: https://github.com/void-linux/xbps/blob/b26f4068b73092aa4e78341dad2b43748dcbdf0a/lib/transaction_commit.c#L179-L212 (following down the `xbps_unpack_binary_pkg` rabbit hole).

**Comment by ericonr** [comment]
I think the `pre-install` semantics are simply unable to be satisfied in this case, because `pre-install` means "something to run *before* the package is installed", but the C library is necessary for anything to run at all.

Maybe it should simply be documented that libc (and even packages providing `/bin/sh`, for that matter) shouldn't have `INSTALL` or `REMOVE` scripts at all. As has been discussed in IRC, that might have been part of the motivation for splitting `glibc-locales` into a subpackage.

**Comment by ArsenArsen** [comment]
Perhaps an easier solution is disabling some actions in `props.plist`? I'm not entirely sure how this could be split off, because I'm not sure how subpackages function in `xbps-src`, but that sounds like the right answer

**Comment by ericonr** [comment]
I would argue that documenting the limitation is the easiest route :stuck_out_tongue: 

Still, a possible solution that still allows for such scripts in these base packages by limiting actions to `pre-remove` and `post-install` sounds interesting (I think only allowing specific steps instead of disabling specific ones would be best). I'm not sure if we want to add this mechanism, but it definitely sounds feasible.

**Comment by ArsenArsen** [comment]
Easiest, sure, but it's also not a complete solution

**Comment by sgn** [comment]
I would argue that if a complete solution requires a ton of code, it doesn't worth it. Let the code serve us, not the otherwise.

**Comment by sgn** [comment]
https://xkcd.com/2021/

**Comment by ArsenArsen** [comment]
@sgn naturally, but the "complete solution" in this case is

1. disabling actions that the package wants to disable (which doesn't sound very hard), or
2. splitting off glibc-gconv, something I'm yet to look into

**Comment by Duncaen** [comment]
The solution is to batch run all pre- scripts before the transaction starts and to run all post- scripts after the full transaction finishes.
Which is the only correct way to run scripts without randomly breaking them within the transaction.

**Comment by Duncaen** [comment]
https://github.com/void-linux/xbps/issues/254

**Comment by Duncaen** [comment]
Should be fixed by https://github.com/void-linux/xbps/pull/410.
